<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm2.aspx.cs" Inherits="FirstProject.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="idLabel" runat="server" Text="Enter Id"></asp:Label><br />
            <asp:TextBox ID="Id" runat="server" ></asp:TextBox><br /><br />
            <asp:Button runat="server" ID="button1" Text="Select"  />
            <br /><br />
            <asp:GridView ID="gridview1" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="True" DataKeyNames="id" onrowdeleting="Delete">
                <Columns>
                    <asp:BoundField  DataField="id" HeaderText="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" />
                    <asp:BoundField DataField="Address" HeaderText="Address" />
                   </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
